#ifndef _CASE_H_
#define _CASE_H_
#define SECRET "@SECRET@"

#include <sstream>
#include <string>

#include "command.h"
#include "test.h"

inline std::string trimEnd(std::string s) {
  s.erase(s.find_last_not_of("\t\n\r\f\v ") + 1);
  return s;
}

inline std::string trimEnd(std::ostringstream& oss) {
  auto s = oss.str();
  s.erase(s.find_last_not_of("\t\n\r\f\v ") + 1);
  return s;
}

TEST_CASE("case4") {
  std::istringstream inputCommand(
      "Insert \"Book\" \"Author\" 2147483647 1\n"
      "Insert \"Book\" \"Author\" -2147483648 1\n"
      "Insert \"Book\" \"Author\" 0 1\n"
      "Insert \"Book\" \"Author\" 999999999 100000\n"
      "Insert \"Book\" \"Author\" -1 3\n"
      "Insert \"Book\" \"Author\" 1 2\n"
      "Insert \"Large\" \"Test\" 1 2147483647\n"
      "Insert \"Large\" \"Test\" 2 2147483646\n"
      "Find Book \"Book\" \"Author\"\n"
      "Borrow \"Book\" \"Author\" 2147483647 \"User\"\n"
      "Borrow \"Book\" \"Author\" -2147483648 \"User\"\n"
      "Borrow \"Book\" \"Author\" 0 \"User\"\n"
      "Borrow \"Book\" \"Author\" -1 \"User\"\n"
      "Borrow \"Book\" \"Author\" 1 \"User\"\n"
      "Return \"Book\" \"Author\" 2147483647 \"User\"\n"
      "Return \"Book\" \"Author\" -2147483648 \"User\"\n"
      "Return \"Book\" \"Author\" 0 \"User\"\n"
      "Return \"Book\" \"Author\" -1 \"User\"\n"
      "Return \"Book\" \"Author\" 1 \"User\"\n"
      "Find Book \"Book\" \"Author\"\n"
      "Insert \"A\" \"Z\" 1 1\n"
      "Insert \"A\" \"Z\" 2 1\n"
      "Insert \"A\" \"Z\" 3 1\n"
      "Insert \"A\" \"Z\" 4 1\n"
      "Insert \"A\" \"Z\" 5 1\n"
      "Insert \"A\" \"Z\" 6 1\n"
      "Insert \"A\" \"Z\" 7 1\n"
      "Insert \"A\" \"Z\" 8 1\n"
      "Insert \"A\" \"Z\" 9 1\n"
      "Insert \"A\" \"Z\" 10 1\n"
      "Insert \"A\" \"Z\" 100 1\n"
      "Insert \"A\" \"Z\" 1000 1\n"
      "Insert \"A\" \"Z\" -100 1\n"
      "Insert \"A\" \"Z\" -1000 1\n"
      "Find Book \"A\" \"Z\"\n"
      "Borrow \"A\" \"Z\" 1 \"B1\"\n"
      "Borrow \"A\" \"Z\" 2 \"B2\"\n"
      "Borrow \"A\" \"Z\" 3 \"B3\"\n"
      "Borrow \"A\" \"Z\" 4 \"B4\"\n"
      "Borrow \"A\" \"Z\" 5 \"B5\"\n"
      "Borrow \"A\" \"Z\" 6 \"B6\"\n"
      "Borrow \"A\" \"Z\" 7 \"B7\"\n"
      "Borrow \"A\" \"Z\" 8 \"B8\"\n"
      "Borrow \"A\" \"Z\" 9 \"B9\"\n"
      "Borrow \"A\" \"Z\" 10 \"B10\"\n"
      "Borrow \"A\" \"Z\" 100 \"B11\"\n"
      "Borrow \"A\" \"Z\" 1000 \"B12\"\n"
      "Borrow \"A\" \"Z\" -100 \"B13\"\n"
      "Borrow \"A\" \"Z\" -1000 \"B14\"\n"
      "Find Book \"A\" \"Z\"\n"
      "Delete Edition \"A\" \"Z\" -1000\n"
      "Delete Edition \"A\" \"Z\" -100\n"
      "Delete Edition \"A\" \"Z\" 1\n"
      "Delete Edition \"A\" \"Z\" 2\n"
      "Delete Edition \"A\" \"Z\" 3\n"
      "Delete Edition \"A\" \"Z\" 4\n"
      "Delete Edition \"A\" \"Z\" 5\n"
      "Delete Edition \"A\" \"Z\" 6\n"
      "Delete Edition \"A\" \"Z\" 7\n"
      "Delete Edition \"A\" \"Z\" 8\n"
      "Delete Edition \"A\" \"Z\" 9\n"
      "Delete Edition \"A\" \"Z\" 10\n"
      "Delete Edition \"A\" \"Z\" 100\n"
      "Delete Edition \"A\" \"Z\" 1000\n"
      "Borrow \"Large\" \"Test\" 1 \"X\"\n"
      "Find Book \"Large\" \"Test\"\n"
      "Borrow \"Large\" \"Test\" 2 \"X\"\n"
      "Find Book \"Large\" \"Test\"\n"
      "Insert \"Title1\" \"Same\" 1 1\n"
      "Insert \"Title2\" \"Same\" 1 1\n"
      "Insert \"Title3\" \"Same\" 1 1\n"
      "Insert \"Title4\" \"Same\" 1 1\n"
      "Insert \"Title5\" \"Same\" 1 1\n"
      "Insert \"Title6\" \"Same\" 1 1\n"
      "Insert \"Title7\" \"Same\" 1 1\n"
      "Insert \"Title8\" \"Same\" 1 1\n"
      "Insert \"Title9\" \"Same\" 1 1\n"
      "Insert \"Title10\" \"Same\" 1 1\n"
      "Find Author \"Same\"\n"
      "Insert \"Same Title\" \"Auth1\" 1 1\n"
      "Insert \"Same Title\" \"Auth2\" 1 1\n"
      "Insert \"Same Title\" \"Auth3\" 1 1\n"
      "Insert \"Same Title\" \"Auth4\" 1 1\n"
      "Insert \"Same Title\" \"Auth5\" 1 1\n"
      "Sort by Title\n"
      "Borrow \"Title1\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title2\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title3\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title4\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title5\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title6\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title7\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title8\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title9\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Title10\" \"Same\" 1 \"Mega\"\n"
      "Borrow \"Same Title\" \"Auth1\" 1 \"Mega\"\n"
      "Borrow \"Same Title\" \"Auth2\" 1 \"Mega\"\n"
      "Borrow \"Same Title\" \"Auth3\" 1 \"Mega\"\n"
      "Borrow \"Same Title\" \"Auth4\" 1 \"Mega\"\n"
      "Borrow \"Same Title\" \"Auth5\" 1 \"Mega\"\n"
      "Delete Edition \"Title1\" \"Same\" 1\n"
      "Delete Edition \"Title2\" \"Same\" 1\n"
      "Delete Edition \"Title3\" \"Same\" 1\n"
      "Sort by Author\n"
      "Return \"Large\" \"Test\" 1 \"X\"\n"
      "Return \"Large\" \"Test\" 2 \"X\"\n"
      "Find Book \"Large\" \"Test\"\n");
  std::ostringstream oss;
  std::streambuf* cout_buf = std::cout.rdbuf();
  std::streambuf* cin_buf = std::cin.rdbuf();
  std::cout.rdbuf(oss.rdbuf());
  std::cin.rdbuf(inputCommand.rdbuf());
  CHECK(true);

  string line;
  while (getline(cin, line)) {
    execute(line);
  }

  auto expected =
      "Insert Author's Book, Edition: 2147483647.;"
      "Insert Author's Book, Edition: -2147483648.;"
      "Insert Author's Book, Edition: 0.;"
      "Insert Author's Book, Edition: 999999999.;"
      "Insert Author's Book, Edition: -1.;"
      "Insert Author's Book, Edition: 1.;"
      "Insert Test's Large, Edition: 1.;"
      "Insert Test's Large, Edition: 2.;"
      "Title: Book	Author: Author	Edition: <-2147483648(1), -1(3), 0(1), "
      "1(2), 999999999(100000), 2147483647(1)>;"
      "User borrows Author's Book, Edition: 2147483647.;"
      "User borrows Author's Book, Edition: -2147483648.;"
      "User borrows Author's Book, Edition: 0.;"
      "User borrows Author's Book, Edition: -1.;"
      "User borrows Author's Book, Edition: 1.;"
      "User returns Author's Book, Edition: 2147483647.;"
      "User returns Author's Book, Edition: -2147483648.;"
      "User returns Author's Book, Edition: 0.;"
      "User returns Author's Book, Edition: -1.;"
      "User returns Author's Book, Edition: 1.;"
      "Title: Book	Author: Author	Edition: <-2147483648(1), -1(3), 0(1), "
      "1(2), 999999999(100000), 2147483647(1)>;"
      "Insert Z's A, Edition: 1.;"
      "Insert Z's A, Edition: 2.;"
      "Insert Z's A, Edition: 3.;"
      "Insert Z's A, Edition: 4.;"
      "Insert Z's A, Edition: 5.;"
      "Insert Z's A, Edition: 6.;"
      "Insert Z's A, Edition: 7.;"
      "Insert Z's A, Edition: 8.;"
      "Insert Z's A, Edition: 9.;"
      "Insert Z's A, Edition: 10.;"
      "Insert Z's A, Edition: 100.;"
      "Insert Z's A, Edition: 1000.;"
      "Insert Z's A, Edition: -100.;"
      "Insert Z's A, Edition: -1000.;"
      "Title: A	Author: Z	Edition: <-1000(1), -100(1), 1(1), 2(1), 3(1), "
      "4(1), 5(1), 6(1), 7(1), 8(1), 9(1), 10(1), 100(1), 1000(1)>;"
      "B1 borrows Z's A, Edition: 1.;"
      "B2 borrows Z's A, Edition: 2.;"
      "B3 borrows Z's A, Edition: 3.;"
      "B4 borrows Z's A, Edition: 4.;"
      "B5 borrows Z's A, Edition: 5.;"
      "B6 borrows Z's A, Edition: 6.;"
      "B7 borrows Z's A, Edition: 7.;"
      "B8 borrows Z's A, Edition: 8.;"
      "B9 borrows Z's A, Edition: 9.;"
      "B10 borrows Z's A, Edition: 10.;"
      "B11 borrows Z's A, Edition: 100.;"
      "B12 borrows Z's A, Edition: 1000.;"
      "B13 borrows Z's A, Edition: -100.;"
      "B14 borrows Z's A, Edition: -1000.;"
      "Title: A	Author: Z	Edition: <-1000(0), -100(0), 1(0), 2(0), 3(0), "
      "4(0), 5(0), 6(0), 7(0), 8(0), 9(0), 10(0), 100(0), 1000(0)>;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "X borrows Test's Large, Edition: 1.;"
      "Title: Large	Author: Test	Edition: <1(2147483646), "
      "2(2147483646)>;"
      "X borrows Test's Large, Edition: 2.;"
      "Title: Large	Author: Test	Edition: <1(2147483646), "
      "2(2147483645)>;"
      "Insert Same's Title1, Edition: 1.;"
      "Insert Same's Title2, Edition: 1.;"
      "Insert Same's Title3, Edition: 1.;"
      "Insert Same's Title4, Edition: 1.;"
      "Insert Same's Title5, Edition: 1.;"
      "Insert Same's Title6, Edition: 1.;"
      "Insert Same's Title7, Edition: 1.;"
      "Insert Same's Title8, Edition: 1.;"
      "Insert Same's Title9, Edition: 1.;"
      "Insert Same's Title10, Edition: 1.;"
      "Same's Books: <Title1, Title10, Title2, Title3, Title4, Title5, Title6, "
      "Title7, Title8, Title9>;"
      "Insert Auth1's Same Title, Edition: 1.;"
      "Insert Auth2's Same Title, Edition: 1.;"
      "Insert Auth3's Same Title, Edition: 1.;"
      "Insert Auth4's Same Title, Edition: 1.;"
      "Insert Auth5's Same Title, Edition: 1.;"
      "Title: A	Author: Z	Edition: <-1000(0), -100(0), 1(0), 2(0), 3(0), "
      "4(0), 5(0), 6(0), 7(0), 8(0), 9(0), 10(0), 100(0), 1000(0)>;"
      "Title: Book	Author: Author	Edition: <-2147483648(1), -1(3), 0(1), "
      "1(2), 999999999(100000), 2147483647(1)>;"
      "Title: Large	Author: Test	Edition: <1(2147483646), "
      "2(2147483645)>;"
      "Title: Same Title	Author: Auth1	Edition: <1(1)>;"
      "Title: Same Title	Author: Auth2	Edition: <1(1)>;"
      "Title: Same Title	Author: Auth3	Edition: <1(1)>;"
      "Title: Same Title	Author: Auth4	Edition: <1(1)>;"
      "Title: Same Title	Author: Auth5	Edition: <1(1)>;"
      "Title: Title1	Author: Same	Edition: <1(1)>;"
      "Title: Title10	Author: Same	Edition: <1(1)>;"
      "Title: Title2	Author: Same	Edition: <1(1)>;"
      "Title: Title3	Author: Same	Edition: <1(1)>;"
      "Title: Title4	Author: Same	Edition: <1(1)>;"
      "Title: Title5	Author: Same	Edition: <1(1)>;"
      "Title: Title6	Author: Same	Edition: <1(1)>;"
      "Title: Title7	Author: Same	Edition: <1(1)>;"
      "Title: Title8	Author: Same	Edition: <1(1)>;"
      "Title: Title9	Author: Same	Edition: <1(1)>;"
      "Mega borrows Same's Title1, Edition: 1.;"
      "Mega borrows Same's Title2, Edition: 1.;"
      "Mega borrows Same's Title3, Edition: 1.;"
      "Mega borrows Same's Title4, Edition: 1.;"
      "Mega borrows Same's Title5, Edition: 1.;"
      "Mega borrows Same's Title6, Edition: 1.;"
      "Mega borrows Same's Title7, Edition: 1.;"
      "Mega borrows Same's Title8, Edition: 1.;"
      "Mega borrows Same's Title9, Edition: 1.;"
      "Mega borrows Same's Title10, Edition: 1.;"
      "Mega borrows Auth1's Same Title, Edition: 1.;"
      "Mega borrows Auth2's Same Title, Edition: 1.;"
      "Mega borrows Auth3's Same Title, Edition: 1.;"
      "Mega borrows Auth4's Same Title, Edition: 1.;"
      "Mega borrows Auth5's Same Title, Edition: 1.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Outstanding borrows exist.;"
      "Title: Same Title	Author: Auth1	Edition: <1(0)>;"
      "Title: Same Title	Author: Auth2	Edition: <1(0)>;"
      "Title: Same Title	Author: Auth3	Edition: <1(0)>;"
      "Title: Same Title	Author: Auth4	Edition: <1(0)>;"
      "Title: Same Title	Author: Auth5	Edition: <1(0)>;"
      "Title: Book	Author: Author	Edition: <-2147483648(1), -1(3), 0(1), "
      "1(2), 999999999(100000), 2147483647(1)>;"
      "Title: Title1	Author: Same	Edition: <1(0)>;"
      "Title: Title10	Author: Same	Edition: <1(0)>;"
      "Title: Title2	Author: Same	Edition: <1(0)>;"
      "Title: Title3	Author: Same	Edition: <1(0)>;"
      "Title: Title4	Author: Same	Edition: <1(0)>;"
      "Title: Title5	Author: Same	Edition: <1(0)>;"
      "Title: Title6	Author: Same	Edition: <1(0)>;"
      "Title: Title7	Author: Same	Edition: <1(0)>;"
      "Title: Title8	Author: Same	Edition: <1(0)>;"
      "Title: Title9	Author: Same	Edition: <1(0)>;"
      "Title: Large	Author: Test	Edition: <1(2147483646), "
      "2(2147483645)>;"
      "Title: A	Author: Z	Edition: <-1000(0), -100(0), 1(0), 2(0), 3(0), "
      "4(0), 5(0), 6(0), 7(0), 8(0), 9(0), 10(0), 100(0), 1000(0)>;"
      "X returns Test's Large, Edition: 1.;"
      "X returns Test's Large, Edition: 2.;"
      "Title: Large	Author: Test	Edition: <1(2147483647), "
      "2(2147483646)>;";

  std::cout.rdbuf(cout_buf);
  std::cin.rdbuf(cin_buf);
  CHECK(trimEnd(oss) == trimEnd(expected));
}

#endif